### PR TITLE
Linear regression as a group added. It wants to be a vectorspace but I n...

### PR DESCRIPTION
**Pull request by snoble**
...eed to understand how the type system works first. Aaaaand I'll add tests.

### CODE REVIEW

**Comment by ianoc** [comment]
Sorry my bad, git foo on cmd line broke stuff and closed all of these

**Comment by mcanlas** [comment]
Looks like a stale PR. Can we close?

**Comment by isnotinvain** [comment]
@snoble ?

**Comment by snoble** [comment]
oh totally... (I don't really remember what this does tbh)

**Comment by isnotinvain** [comment]
Thanks! :)

**Pull request closed without merging**
