### PR TITLE
Replace BloomFilter underlying BitSet with cats-collections immutable BitSet

### PR DESCRIPTION
**Pull request by regadas**
See #716 for context.

Update: https://github.com/twitter/algebird/issues/716#issuecomment-575951635

### CODE REVIEW

**Comment by johnynek** [comment]
If we are going to make a new implementation, I'd like to explore a pattern @non and I have found for parameterized monoids:
```scala
final class BloomFilter[A](hashes: Int, width: Int)(implicit val hasher: Hasher[A]) {
  sealed class BF[A] {
    def mightContain(a: A): Boolean
  }

  final case class BFInstance[A](toValue: A) extends BF[A]
  final case class BFSet(toBitSet: BitSet) extends BF[A]
  // ...

  def apply(a: A): BF[A] = ...

  implicit val monoid: Monoid[BF[A]] = ...
}
```

Then you use it with:

```scala
val bloomFilter: BloomFilter[A] = new BloomFilter(4, 1024)

val itemA1: bloomFilter.BF[A] = bloomFilter(a1)
val itemA2: bloomFilter.BF[A] = bloomFilter(a2)

val a3 = Monoid.plus(itemA1, itemA2)
```
Now, the type system prevents us from confusing bloom filter values from different parameter sets. Also, the serializers can be inside `BloomFilter` which knows the parmeters, so you don't need to serialize the parameters with each value.

**Comment by johnynek** [comment]
what do you think?

**Comment by regadas** [comment]
Sounds good! ... I've been meaning to pick this up again! I'll explore that!

A few notes around this PR:

* I moved the current impl to a legacy package ... I'll probably move it back (keep things as is) and add the new impl in a new package. (it will be opt in)

* I really think the BitSet impl as potential and as I mentioned in the comment, perf wise is on par and slightly better in some cases. When it comes to `createBloomFilterUsingFold` and `createBloomFilterAggregator` from #672 I saw significant improvements as well.

* I think you and @non already did some ground work in https://github.com/typelevel/cats-collections/pull/184 some things in this impl are a mix of that with the impl from master. Not sure what the move is ... if we cleanup that impl and merge it (we would depend on cats-collections) or we copy the impl (this gives us more freedom to tap into private mutable methods when needed to)

**Review by regadas — COMMENTED** [review]
Closing this in favour of #840

**Pull request closed without merging**
