### PR TITLE
Add kind-projector

### PR DESCRIPTION
**Pull request by regadas**

### CODE REVIEW

**Review by johnynek — APPROVED** [review]
Thanks!

**Comment by regadas** [comment]
@johnynek thanks for taking a look! 

PS: I'll revise CI here as well

**Comment by johnynek** [comment]
looks like running tut to build the documentation failed, I think. Maybe the plugins somehow didn't get passed through to something there?

Side note: if we are cleaning things up, using mdoc would be nice at some point in the future.

**Comment by johnynek** [comment]
This is great, thanks!

The next release is shaping up nicely.

**Pull request merged**
