### PR TITLE
Convert all laws to take Equiv instances, deprecate Equiv versions

### PR DESCRIPTION
**Pull request by sritchie**
This PR converts all laws (and all tests!) to take Equiv instances by default. This is a binary-incompatible change, but in functions that take lots of implicit arguments that shouldn't be passed by default anyway.

All `LawsEquiv` versions have a deprecation warning and point to the actual `Laws`.

This also adds `.jvmopts` to, hopefully, speed up the build.

### CODE REVIEW

**Comment by sritchie** [comment]
Holy shit... those jvm opts dropped the build time from 40something minutes to 7 minutes on the `2.11` build.

**Comment by sritchie** [comment]
@ianoc looks like these started running out of permgen space. Probably need to redo them one at a time.

**Comment by ianoc** [comment]
@sritchie Yeah looks like that. Lets not worry about it in this PR. The last one failed though. is that test reasonably flaky?

**Comment by ianoc** [comment]
Thanks for running the tests you did btw!

**Comment by sritchie** [comment]
@ianoc ah, yes, that one is, and we have an issue for it, I believe. kicking it off again

**Comment by sritchie** [comment]
here we go: https://github.com/twitter/algebird/issues/508

**Comment by sritchie** [comment]
💥  tests pass @ianoc @johnynek.

**Comment by johnynek** [comment]
💯

**Pull request merged**
