### PR TITLE
upgrade scalacheck

### PR DESCRIPTION
**Pull request by MansurAshraf**
Bringing it to the same version as used internally

### CODE REVIEW

**Comment by MansurAshraf** [comment]
Following test is failing after the upgrade 

[info] - map int double scaling *** FAILED ***
[info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
[info]    (CheckProperties.scala:12)
[info]     Falsified after 1 successful property evaluations.
[info]     Location: (CheckProperties.scala:12)
[info]     Occurred when passed generated values (
[info]       arg0 = Map(1039802616 -> 4.4384666053440264E176),
[info]       arg1 = 4.151844009363087E158,
[info]       arg2 = 7.086895641185986E-105
[info]     )

**Comment by ianoc** [comment]
Sorry my bad, git foo on cmd line broke stuff and closed all of these

**Comment by DanielleSucher** [comment]
Looks like `map int double scaling` now passes and instead we've moved onto a different failure:

```
[info] - should correctly downsize sparse HLL *** FAILED ***
[info]   0.09900977968481595 was not less than 0.056875 (HyperLogLogTest.scala:127)
```

**Comment by ianoc** [comment]
This branch seems old @DanielleSucher, you want to take this effort over in a new PR maybe? 

-- That test btw is probabilistic so can just fail with a false positive so unless it fails always its probably not broken

**Comment by DanielleSucher** [comment]
@ianoc - Sure, though I was actually thinking of going back and triaging (and seeing which could be closed of) a bunch of old branches here, too.

(Hopefully https://github.com/twitter/algebird/pull/478 will help re the probabilistic tests!)

**Comment by DanielleSucher** [comment]
@ianoc Let's close this one now ^^

**Comment by ianoc** [comment]
Good call, closed

**Pull request closed without merging**
