### PR TITLE
Update README and version as part of Algebird release

### PR DESCRIPTION
**Pull request by piyushnarang**
Corresponds to release: https://github.com/twitter/algebird/releases/tag/0.13.0. Currently the release is marked as a 'pre-release', can update that if folks don't have objections.

### CODE REVIEW

**Comment by sritchie-stripe** [comment]
Oh no, @piyushnarang, this next version was supposed to be 0.13.0 - we pushed a bunch of binary incompatible changes specifically for this reason. I think we're going to have to do the release dance once again for 0.13.0 and make a note on this version. We already broke binary compatibility going to 0.12.2 or 0.12.3, I believe, so I want to make sure we get this one right.

**Comment by sritchie-stripe** [comment]
Ah, if it's a pre-release that's great. Guess that means we can still update.

**Comment by piyushnarang** [comment]
@sritchie ah ok, was not aware that we wanted to bump to 0.13. I can publish this as 0.13.0 and update the notes to mark it as the next release. Will get to that tomorrow.

**Comment by sritchie-stripe** [comment]
@piyushnarang thanks!

**Comment by johnynek** [comment]
Well, I have a few tiny things more if we can wait till Thursday. Sorry. I
have not had a lot of time.

**Comment by piyushnarang** [comment]
@johnynek sure, you want to get some PRs in before? Can wait a couple more days.

**Comment by oscar-stripe** [comment]
👍

**Pull request merged**
